### ISSUE TITLE
Stuck in Player 1 screen

### ISSUE THREAD

**Issue by CloneHeroUruguay** [EliteAsian123/YARG#12]
![image](https://user-images.githubusercontent.com/110006088/224465377-61421354-9908-439f-9560-27de5b7a4f6b.png)

I get to load some clone hero charts, but I get stuck on that screen after hitting play with my mouse. I am able to go back by pressing the left arrow on the screen.

Does this game support .chart format?

And while I'm at it, will this game have full mouse support? That would be huge for newcomers.

**Comment by EliteAsian123** [comment]
> I get to load some clone hero charts, but I get stuck on that screen after hitting play with my mouse. I am able to go back by pressing the left arrow on the screen.

This happens when you haven't added a player yet. On the main menu, click on `Add/Edit Players` and add a player before clicking play.

> Does this game support .chart format?

Not yet, but planned. I will make an issue for it.

> And while I'm at it, will this game have full mouse support? That would be huge for newcomers.

No, but it shouldn't be too hard to implement. I'll open a separate issue for that as well.

For now, I will close the issue. Please re-open it if the issue still persists after you add a player. Thanks!
