### ISSUE TITLE
(Bug) Audio becomes desynced over the course of a song

### ISSUE THREAD

**Issue by LegoMaster09** [EliteAsian123/YARG#17]
I was playing some longer songs, and it seems like the audio slowly desyncs and gets later, which makes it pretty difficult to hit any notes.

**Comment by EliteAsian123** [comment]
Huh. That is odd, and should not happen *unless* of a huge lag spike. 

Can you provide an example of a song where this happens? (just the name and source is fine). 
Can you also tell me if you were lag spiking or not?

Thanks for the issue report, and apologies for the inconvinience.

**Comment by LegoMaster09** [comment]
I was playing Painkiller by Judas Priest and Green Grass and High Tides by The Outlaws(Wavegroup), both of them come from that spreadsheet of songs from Clone Hero: https://docs.google.com/spreadsheets/u/0/d/13B823ukxdVMocowo1s5XnT3tzciOfruhUVePENKc01o/htmlview#gid=0

**Comment by LegoMaster09** [comment]
I also have to play on low quality mode, otherwise the game is very laggy.

**Comment by EliteAsian123** [comment]
Thanks for the info, I'll investigate it ASAP.

**Comment by EliteAsian123** [comment]
Howdy. Through some investigation, my *assumption* is that when the game lags, the audio doesn't, which causes desync. To prevent this, I added an option in the settings menu that bases the current time on the audio *instead* of Unity's delta-time (which is what was being used).

Now, there are some issues attached with basing the time off of the audio instead of the game time, but I think that it *may* solve the problem you are having.

Below, I attached a zip-file containing the current dev-build. If you don't mind, can you test to see if this fixes the problem for you? Be sure to go into the settings and turn “Use Audio Time” **on**. Please be advised that the settings do not save between session yet.

If this fixes the issue, please close this issue. If not, please let me know. Thanks!

**Comment by LegoMaster09** [comment]
This seems to have fixed the issue, although now songs don't end.

**Comment by EliteAsian123** [comment]
Okay, thanks for testing! Yes, I forgot to account for the song ending with the new setting, so that will be fixed with the next release.

**Comment by EliteAsian123** [comment]
I've fixed the song ending issue. If you'd like to continue playing, here is a dev-build hot-fix. Thanks again!
https://drive.google.com/file/d/1deLy0nuYRkjHyFlwFo1MOrY7b7ZeUhiT/view
